[package]
name = "rust-mock-client"
version = "0.1.0"
authors = ["Richard Barnes <rlb@ipv.sx>"]
edition = "2018"

[dependencies]
tonic = "0.3"
prost = "0.6"
tokio = { version = "1.18", features = ["macros"] }
clap = "3.0.0-beta.2"

[build-dependencies]
tonic-build = "0.3"
